name: ipydrawio

channels:
  - conda-forge
  - nodefaults

dependencies:
  - black
  - doit
  - firefox =78
  - flake8
  - geckodriver >=0.28.0
  - ipywidgets >=7.6
  - isort >=5
  - jedi <0.18.0
  - jupyterlab >=3.0.6,<4.0.0a0
  - jupyterlab_widgets >=1
  - lxml
  - nodejs >=12,<13.0.0a0
  - pillow
  - pip
  - pyflakes
  - pypdf2
  - pytest
  - pytest-cov
  - python
  - requests_cache
  - robotframework
  - robotframework-lint
  - robotframework-pabot
  - robotframework-seleniumlibrary
  - twine
  - wheel
