name: jupyterlab-drawio

channels:
  - conda-forge
  - nodefaults

dependencies:
  - black
  - doit
  - firefox =78
  - flake8
  - geckodriver >=0.28.0
  - isort <5
  - jupyterlab >=2.2.4,<3.0.0a0
  - lxml
  - nodejs >=12,<13.0.0a0
  - pillow
  - pip
  - pyflakes
  - pypdf2
  - pytest
  - pytest-cov
  - python
  - requests_cache
  - robotframework
  - robotframework-lint
  - robotframework-pabot
  - robotframework-seleniumlibrary
  - twine
  - wheel
