name: jupyterlab-drawio

channels:
  - conda-forge

dependencies:
  - black
  - doit ==0.32
  - flake8
  - isort <5
  - jupyterlab >=2.2.4,<3.0.0a0
  - nodejs >=12,<13.0.0a0
  - pip
  - pyflakes
  - pytest
  - python
  - requests_cache
  - twine
  - wheel
