name: ipydrawio

channels:
  - conda-forge
  - nodefaults

dependencies:
  - ipywidgets >=7.6
  - jupyterlab >=3.0.6,<4.0.0a0
  - jupyterlab_widgets >=1
  - lxml
  - networkx
  - nodejs >=12,<13.0.0a0
  - pandas
  - pillow
  - pypdf2
  - shapely
  - tabulate
  # linting and testing
  - babel
  - black
  - doit
  - flake8
  - httpx
  - isort <5
  - json-e
  - pyflakes
  - pytest
  - requests_cache
  - robotframework
  - robotframework-lint
  - robotframework-jupyterlibrary
  - robotframework-pabot
  # python cruft
  - python >=3.8,<3.9.0a0
  - pip
  - twine
  - wheel
  # demo toys
  - matplotlib-base
  - jupyter-lsp-python-plugins
  - jupyterlab-classic
  - jupyterlab-lsp
  - nbgitpuller
  - wxyz_datagrid
  - wxyz_lab
  - bqplot
  # for graphviz2drawio
  - raven
  - python-graphviz
  - pygraphviz
  # for ipython
  - jedi <0.18.0
  # binder pins
  - jupyter_telemetry >=0.1.0 # ick, but fails pip check
  - pip:
      - graphviz2drawio
