name: jupyterlab-drawio

channels:
  - conda-forge
  - nodefaults

dependencies:
  - babel
  - black
  - bqplot
  - doit
  - flake8
  - httpx
  - ipywidgets
  - isort <5
  - json-e
  - jupyterlab >=2.2.4,<3.0.0a0
  - lxml
  - matplotlib-base
  - networkx
  - nodejs >=12,<13.0.0a0
  - pandas
  - pillow
  - pip
  - pyflakes
  - pygraphviz
  - pypdf2
  - pytest
  - python >=3.8,<3.9.0a0
  - requests_cache
  - shapely
  - tabulate
  - twine
  - wheel
  - pip:
      - graphviz2drawio
